### ISSUE TITLE
关于收敛性实验

### ISSUE THREAD

**Issue by Jinzeyuu** [jinhong-ni/DEQFusion#4]
您好，作者。从你的论文中发现DEQ融合的收敛性也是较好，但没有理解到如何进行的收敛实验过程，如果您方便的话，可否提供一下相关讲解及源代码。

**Comment by jinhong-ni** [comment]
Convergence is measured by the difference norm between the solutions of two consecutive solver steps, and we say it converges if the difference norm is sufficiently small. To track the convergence, simply compute and print the difference norm between solver steps.
